INSERT INTO config_category VALUES (1, 'General', 0, true);
INSERT INTO config_category VALUES (2, 'L2A Atmospheric Corrections', 1, true);
INSERT INTO config_category VALUES (3, 'S2A L3A Composite', 2, true);
INSERT INTO config_category VALUES (4, 'L3B Vegetation Status', 3, true);
INSERT INTO config_category VALUES (5, 'S2A L4A Crop Mask', 5, true);
INSERT INTO config_category VALUES (6, 'S2A L4B Crop Type', 6, true);
INSERT INTO config_category VALUES (7, 'Archiver', 7, true);
INSERT INTO config_category VALUES (8, 'Executor', 8, false);
INSERT INTO config_category VALUES (12, 'Dashboard', 9, false);
INSERT INTO config_category VALUES (13, 'Monitoring Agent', 10, false);
INSERT INTO config_category VALUES (14, 'Resources', 11, false);
INSERT INTO config_category VALUES (15, 'Downloader', 12, true);
INSERT INTO config_category VALUES (17, 'Site', 14, false);
INSERT INTO config_category VALUES (18, 'S2A L3E Pheno NDVI', 4, true);
INSERT INTO config_category VALUES (19, 'S4C L4B Grassland Mowing', 15, true);
INSERT INTO config_category VALUES (20, 'S4C L4C Agricultural Practices', 16, true);
INSERT INTO config_category VALUES (21, 'LPIS', 17, true);
INSERT INTO config_category VALUES (22, 'S4C L4A Crop Type', 22, true);
INSERT INTO config_category VALUES (23, 'S1 L2 Pre-processor', 23, true);
INSERT INTO config_category VALUES (24, 'S2A L3C LAI N-Days Reprocessing', 4, true);
INSERT INTO config_category VALUES (25, 'S2A L3D LAI Fitted Reprocessing', 4, true);
INSERT INTO config_category VALUES (26, 'S4C Markers Database 1', 26, true);
INSERT INTO config_category VALUES (27, 'Validity Flags', 17, true);
INSERT INTO config_category VALUES (28, 'L4 Permanent crops', 27, true);
INSERT INTO config_category VALUES (29, 'L3 Yield', 28, true);
INSERT INTO config_category VALUES (30, 'L4 Crop Mapping', 29, true);
INSERT INTO config_category VALUES (31, 'FMask', 18, true);
INSERT INTO config_category VALUES (32, 'T-Rex Updater', 32, false);
INSERT INTO config_category VALUES (33, 'S1 Composite', 33, true);
INSERT INTO config_category VALUES (34, 'Biophysical Indicators Composite', 34, true);
INSERT INTO config_category VALUES (35, 'Zarr Converter', 35, true);
INSERT INTO config_category VALUES (36, 'Parcel heterogeneity', 36, true);
INSERT INTO config_category VALUES (37, 'Bare soil detection', 37, true);
INSERT INTO config_category VALUES (38, 'L3 Yield SU', 38, true);
INSERT INTO config_category VALUES (39, 'ERA5', 39, true);
INSERT INTO config_category VALUES (40, 'S4C L4 Change Detection', 40, true);

