insert into crop_list_n3(code_n3, name, code_n2) values (111, 'Wheat', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (112, 'Maize', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (113, 'Rice', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (114, 'Sorghum', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (115, 'Barley', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (116, 'Rye', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (117, 'Oats', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (118, 'Millets', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (119, 'Other cereals', 11);
insert into crop_list_n3(code_n3, name, code_n2) values (121, 'Leafy or stem vegetables', 12);
insert into crop_list_n3(code_n3, name, code_n2) values (122, 'Fruit-bearing vegetables', 12);
insert into crop_list_n3(code_n3, name, code_n2) values (123, 'Root, bulb or tuberous vegetables', 12);
insert into crop_list_n3(code_n3, name, code_n2) values (124, 'Mushrooms and truffles', 12);
insert into crop_list_n3(code_n3, name, code_n2) values (129, 'Other vegetables', 12);
insert into crop_list_n3(code_n3, name, code_n2) values (141, 'Soya beans', 14);
insert into crop_list_n3(code_n3, name, code_n2) values (142, 'Groundnuts', 14);
insert into crop_list_n3(code_n3, name, code_n2) values (143, 'Other oilseed crops', 14);
insert into crop_list_n3(code_n3, name, code_n2) values (151, 'Potatoes', 15);
insert into crop_list_n3(code_n3, name, code_n2) values (152, 'Sweet potatoes', 15);
insert into crop_list_n3(code_n3, name, code_n2) values (153, 'Cassava', 15);
insert into crop_list_n3(code_n3, name, code_n2) values (154, 'Yams', 15);
insert into crop_list_n3(code_n3, name, code_n2) values (159, 'Other root/tuber crops', 15);
insert into crop_list_n3(code_n3, name, code_n2) values (161, 'Spice crops', 16);
insert into crop_list_n3(code_n3, name, code_n2) values (162, 'Beverage crops', 16);
insert into crop_list_n3(code_n3, name, code_n2) values (171, 'Beans', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (172, 'Broad beans', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (173, 'Chickpeas', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (174, 'Cow peas', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (175, 'Lentils', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (176, 'Lupins', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (177, 'Peas', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (178, 'Pigeon peas', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (179, 'Other leguminous crops', 17);
insert into crop_list_n3(code_n3, name, code_n2) values (181, 'Sugar beet', 18);
insert into crop_list_n3(code_n3, name, code_n2) values (182, 'Sugar cane', 18);
insert into crop_list_n3(code_n3, name, code_n2) values (183, 'Sweet sorghum', 18);
insert into crop_list_n3(code_n3, name, code_n2) values (189, 'Other sugar crops', 18);
insert into crop_list_n3(code_n3, name, code_n2) values (191, 'Grasses and other fodder crops', 19);
insert into crop_list_n3(code_n3, name, code_n2) values (192, 'Fibre crops', 19);
insert into crop_list_n3(code_n3, name, code_n2) values (193, 'Medicinal, aromatic, pesticidal or similar crops', 19);
insert into crop_list_n3(code_n3, name, code_n2) values (194, 'Flower crops', 19);
insert into crop_list_n3(code_n3, name, code_n2) values (199, 'Other annual crops', 19);
insert into crop_list_n3(code_n3, name, code_n2) values (211, 'No citrus fruits trees', 21);
insert into crop_list_n3(code_n3, name, code_n2) values (212, 'Citrus fruits trees', 21);
insert into crop_list_n3(code_n3, name, code_n2) values (213, 'Other fruits trees', 21);
insert into crop_list_n3(code_n3, name, code_n2) values (221, 'Vineyards', 22);
insert into crop_list_n3(code_n3, name, code_n2) values (231, 'Olive groves', 23);
insert into crop_list_n3(code_n3, name, code_n2) values (241, 'Trees', 24);
insert into crop_list_n3(code_n3, name, code_n2) values (311, 'Grassland', 31);
insert into crop_list_n3(code_n3, name, code_n2) values (411, 'Fallows', 41);
insert into crop_list_n3(code_n3, name, code_n2) values (511, 'Shrub land', 51);
insert into crop_list_n3(code_n3, name, code_n2) values (611, 'Conifers', 61);
insert into crop_list_n3(code_n3, name, code_n2) values (621, 'Deciduous slow growth', 62);
insert into crop_list_n3(code_n3, name, code_n2) values (622, 'Deciduous rapid growth', 62);
insert into crop_list_n3(code_n3, name, code_n2) values (631, 'Conifers and deciduous', 63);
insert into crop_list_n3(code_n3, name, code_n2) values (711, 'Sparsely vegetated', 71);
insert into crop_list_n3(code_n3, name, code_n2) values (721, 'Bare soils', 72);
insert into crop_list_n3(code_n3, name, code_n2) values (811, 'Urban', 81);
insert into crop_list_n3(code_n3, name, code_n2) values (821, 'Industrial and commercial', 82);
insert into crop_list_n3(code_n3, name, code_n2) values (831, 'Transport', 83);
insert into crop_list_n3(code_n3, name, code_n2) values (841, 'Greenhouses', 84);
insert into crop_list_n3(code_n3, name, code_n2) values (851, 'Other build-up surface', 85);
insert into crop_list_n3(code_n3, name, code_n2) values (911, 'Sea and coastal lagoons', 91);
insert into crop_list_n3(code_n3, name, code_n2) values (921, 'Inland waters', 91);
insert into crop_list_n3(code_n3, name, code_n2) values (0, 'Unknown', 0);
insert into crop_list_n3(code_n3, name, code_n2) values (291, 'Succulent plant', 29);
insert into crop_list_n3(code_n3, name, code_n2) values (299, 'Other perennial crops', 29);
insert into crop_list_n3(code_n3, name, code_n2) values (319, 'Grassland and meadows', 31);
insert into crop_list_n3(code_n3, name, code_n2) values (699, 'Forest', 69);
insert into crop_list_n3(code_n3, name, code_n2) values (919, 'Water bodies', 91);
