insert into crop_list_n2(code_n2, name, code_n1) values (11, 'Cereals', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (12, 'Vegetables and melons', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (14, 'Oilseed crops', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (15, 'Root/tuber crops with high starch or insulin content', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (16, 'Beverage and spice crops', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (17, 'Leguminous crops', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (18, 'Sugar crops', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (19, 'Other annual crops', 1);
insert into crop_list_n2(code_n2, name, code_n1) values (21, 'Fruits trees', 2);
insert into crop_list_n2(code_n2, name, code_n1) values (22, 'Vineyards', 2);
insert into crop_list_n2(code_n2, name, code_n1) values (23, 'Olive groves', 2);
insert into crop_list_n2(code_n2, name, code_n1) values (24, 'Trees', 2);
insert into crop_list_n2(code_n2, name, code_n1) values (31, 'Grassland and meadows', 3);
insert into crop_list_n2(code_n2, name, code_n1) values (41, 'Fallows', 4);
insert into crop_list_n2(code_n2, name, code_n1) values (51, 'Shrub land', 5);
insert into crop_list_n2(code_n2, name, code_n1) values (61, 'Conifers', 6);
insert into crop_list_n2(code_n2, name, code_n1) values (62, 'Deciduous', 6);
insert into crop_list_n2(code_n2, name, code_n1) values (71, 'Sparsely vegetated', 7);
insert into crop_list_n2(code_n2, name, code_n1) values (72, 'Bare soils', 7);
insert into crop_list_n2(code_n2, name, code_n1) values (81, 'Urban', 8);
insert into crop_list_n2(code_n2, name, code_n1) values (82, 'Industrial and commercial', 8);
insert into crop_list_n2(code_n2, name, code_n1) values (83, 'Transport', 8);
insert into crop_list_n2(code_n2, name, code_n1) values (84, 'Greenhouses', 8);
insert into crop_list_n2(code_n2, name, code_n1) values (85, 'Other build-up surface', 8);
insert into crop_list_n2(code_n2, name, code_n1) values (91, 'Water bodies', 9);
insert into crop_list_n2(code_n2, name, code_n1) values (63, 'Conifers and deciduous', 6);
insert into crop_list_n2(code_n2, name, code_n1) values (0, 'Unknown', 0);
insert into crop_list_n2(code_n2, name, code_n1) values (29, 'Other perennial crops', 2);
insert into crop_list_n2(code_n2, name, code_n1) values (69, 'Forest', 6);
