FROM sen4x/gdal-py:3.9.1

COPY export-product-launcher.py /usr/local/bin
COPY export-product.py /usr/local/bin
COPY import-product-details.py /usr/local/bin
COPY crop-type-parcels2.py /usr/local/bin
COPY remap-confusion-matrix.py /usr/local/bin
COPY sample-selection.py /usr/local/bin
COPY crop-map-s4s.py /usr/local/bin
