FROM sen4x/gdal-py:3.3.2

COPY data-preparation.py /usr/bin
COPY read_shp_cols.py /usr/bin
COPY s4c_l4b_import_config.py /usr/bin
COPY s4c_l4c_export_all_practices.py /usr/bin
COPY s4c_l4c_import_config.py /usr/bin
COPY s4c_l4c_import_practice.py /usr/bin
