FROM sen4x/gdal-py:3.3.2

COPY check_shp.py /usr/bin
COPY data-preparation.py /usr/bin
COPY data-preparation-s4s.py /usr/bin
COPY read_shp_cols.py /usr/bin
COPY s4c_l4b_import_config.py /usr/bin
COPY s4c_l4c_export_all_practices.py /usr/bin
COPY s4c_l4c_import_config.py /usr/bin
COPY s4c_l4c_import_practice.py /usr/bin
COPY s4c_mdb3_input_tables.py /usr/bin
COPY t-rex-genconfig.py /usr/bin
COPY sen2agri_import_uploaded_insitu.py /usr/bin
COPY s4s-yield-safy-params-import.py /usr/bin
COPY s4s-yield-su-historical-data-import.py /usr/bin
