version: '3.0'
services:
    db:
        image: postgis/postgis:11-3.0
        environment:
            POSTGRES_PASSWORD: sen2agri
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data
            - /var/run/postgresql:/var/run/postgresql
        restart: unless-stopped
    t-rex:
        image: sourcepole/t-rex
        command: ["serve", "-c", "/var/lib/t-rex/t-rex.toml"]
        ports:
            - "6767:6767"
        volumes:
            - /var/lib/t-rex:/var/lib/t-rex
        restart: unless-stopped
