cmake_minimum_required(VERSION 3.11)
project(sen2agri-processors-re)

find_package(OTB CONFIG REQUIRED)
find_package(Boost CONFIG REQUIRED COMPONENTS filesystem serialization unit_test_framework)
find_package(CURL CONFIG REQUIRED)

add_subdirectory(BackscatterTemporalFeatures)
add_subdirectory(ClassRemapping)
add_subdirectory(ClassStatistics)
add_subdirectory(ClassStatisticsRatio)
add_subdirectory(CoherenceMonthlyFeatures)
add_subdirectory(MeanComposite)
add_subdirectory(S4SCMSpectralIndices)
add_subdirectory(S4SCMSpectralIndicesStatistics)
add_subdirectory(S4SCMRedEdgeFeatures)
add_subdirectory(StandardDeviation)
add_subdirectory(TemporalResampling)
